import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages, setRequestLocale } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { locales, type Locale, isRtlLocale } from '@/config/i18n';
import { ThemeProvider } from '@/components/theme-provider';
import "@/styles/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const alienRobot = localFont({
  src: "../../styles/fonts/Alien Robot.ttf",
  variable: "--font-alien-robot",
  display: "swap",
});

const bigPixel = localFont({
  src: "../../styles/fonts/Big Pixel demo.otf",
  variable: "--font-big-pixel",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return locales.map((locale) => ({ local: locale }));
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ local: string }>;
}>) {
  const { local } = await params;
  
  // Validate locale
  if (!locales.includes(local as Locale)) {
    notFound();
  }

  // Enable static rendering
  setRequestLocale(local);

  const messages = await getMessages();
  const locale = local as Locale;

  return (
    <html lang={locale} dir={isRtlLocale(locale) ? 'rtl' : 'ltr'} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${alienRobot.variable} ${bigPixel.variable} antialiased`}
      >
        <ThemeProvider>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
